export const projects = [
  {
    id: "traveloper",
    title: "Traveloper",
    period: "2025.08 ~ 2025.10",
    team: "1인 (개인)",
    role: "풀스택",
    tech: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"] as const,
    description: "해외여행 중 지출을 관리하는 서비스",
    details: "Server Actions를 활용한 서버 로직 구현...",
    link: "https://traveloper.vercel.app",
    github: "https://github.com/mewmaze/Traveloper",
    image: "/traveloper.png",
  },
  {
    id: "ss",
    title: "Traveloper",
    period: "2025.08 ~ 2025.10",
    team: "1인 (개인)",
    role: "풀스택",
    tech: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"] as const,
    description: "해외여행 중 지출을 관리하는 서비스",
    details: "Server Actions를 활용한 서버 로직 구현...",
    link: "https://traveloper.vercel.app",
    github: "https://github.com/mewmaze/Traveloper",
    image: "/traveloper.png",
  },
  {
    id: "dr",
    title: "Traveloper",
    period: "2025.08 ~ 2025.10",
    team: "1인 (개인)",
    role: "풀스택",
    tech: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"] as const,
    description: "해외여행 중 지출을 관리하는 서비스",
    details: "Server Actions를 활용한 서버 로직 구현...",
    link: "https://traveloper.vercel.app",
    github: "https://github.com/mewmaze/Traveloper",
    image: "/traveloper.png",
  },
  {
    id: "dper",
    title: "Traveloper",
    period: "2025.08 ~ 2025.10",
    team: "1인 (개인)",
    role: "풀스택",
    tech: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS"] as const,
    description: "해외여행 중 지출을 관리하는 서비스",
    details: "Server Actions를 활용한 서버 로직 구현...",
    link: "https://traveloper.vercel.app",
    github: "https://github.com/mewmaze/Traveloper",
    image: "/traveloper.png",
  },
] as const;
export type Project = (typeof projects)[number];
